# generic_scripts/sanitised_anr.py
import logging
import sys
from pathlib import Path

from generic_scripts.utils.hive_connection import get_hive_connection

# Initialize logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

def read_etl_batch_id(source_system):
    """Read ETL batch ID generated by the batch initialization step."""

    file_path = Path("/opt/project") / "parfiles" / source_system / "etl_batch_id.txt"

    logger.info(
        "[BATCH] Reading batch metadata | path=%s",
        file_path,
    )

    with open(file_path, "r", encoding="utf-8") as file:
        etl_batch_id = file.readline().strip()

    logger.info(
        "[BATCH] Loaded batch_id=%s",
        etl_batch_id,
    )

    return etl_batch_id



def insert_batch_audit_log(cursor, conn, source_system, group, phase_name="sanitised"):
    """
    Update audit.batch_log with ANR (Audit & Reconciliation) result for Sanitised phase based on the inputs of recon_log.
    """

    etl_batch_id = read_etl_batch_id(source_system)


    recon_query = """
        SELECT
        COALESCE(SUM(record_count_processed),0),
        COALESCE(SUM(record_count_failed),0),
        COUNT(*) FILTER (WHERE recon_status = 'E')
        FROM audit.recon_log
        WHERE etl_batch_id = %s
          AND phase_name = %s
          and group_name = %s
          and source_system = %s;
        """
    
    try:
        cursor.execute(
            recon_query,
            (
                etl_batch_id,
                phase_name,
                group,
                source_system
                
            )
        )
        result = cursor.fetchone()

        if not result:
            raise Exception(
                "No reconciliation result found"
            )

        processed_count, failed_count, error_groups = result

        logger.info(
            "[ANR] Recon fetched successfully | batch_id=%s | group=%s",
            etl_batch_id,
            group.upper(),
        )
    except Exception:
        logger.exception(
            "[ANR] Failed to fetch audit.recon_log | batch_id=%s",
            etl_batch_id,
        )
        raise  
    
    
    if error_groups == 0:
        batch_status = "C"
        error_message = "Reconciliation passed."
    else:
        batch_status = "E"
        error_message = (
        f"{error_groups} reconciliation group(s) failed."
        )

    query = """
        INSERT INTO audit.batch_log (
            etl_batch_id,
            phase_name,
            source_system,
            batch_status,
            record_count_processed,
            record_count_failed,
            error_message,
            created_at,
            updated_at
        )
        VALUES (
            %s,
            %s,
            %s,
            %s,
            %s,
            %s,
            %s,
            CURRENT_TIMESTAMP,
            CURRENT_TIMESTAMP
        );
        """

    try:
        cursor.execute( query,
        (
            etl_batch_id,
            phase_name,
            source_system,
            batch_status,
            processed_count,
            failed_count,
            error_message,
        ),
        )

        logger.info(
            "[ANR] Audit inserted successfully | batch_id=%s | status=%s",
            etl_batch_id,
            batch_status.upper(),
        )

        return batch_status

    except Exception:

        logger.exception(
            "[ANR] Failed inserting audit.batch_log | batch_id=%s",
            etl_batch_id,
        )

        raise
    

def main():
    """Main entry point for batch_log_insertion"""
    # Validate arguments
    if len(sys.argv) != 3:
        print("Usage: python batch_log_insertion.py <group_number> <source_system>")
        sys.exit(1)
    
    group = sys.argv[1]
    source_system = sys.argv[2]
    
    conn = None
    cursor = None

    try:
        # Connect to database
        conn = get_hive_connection()
        if conn:
            cursor = conn.cursor()
            logger.info("Connected successfully to Hive")
        else:
            logger.error("Can't connect to Hive. Please check DB availability.")
            sys.exit(1)

        
        # Call audit function
        audit_status = insert_batch_audit_log(cursor, conn, source_system, group,  phase_name="sanitised")
        
        if audit_status == "E":
            logger.error(
                f"[ANR] Count reconciliation failed for the tables in group {group}"
            )
            sys.exit(1)
        elif audit_status == "C":
            logger.info(f"Audit is successful for the tables in group {group} ")    
            
    
    except Exception as e:
        logger.error(f"Fatal error: {e}")
        sys.exit(1)
    finally:
        # Cleanup
        if cursor:
            cursor.close()
        if conn:
            conn.close()
        logger.info("Closed Connection to Hive")

        
if __name__ == "__main__":
    main()    