from datetime import datetime
import logging
import sys
import os
import json

from annotated_types import UpperCase
from generic_scripts.utils.hive_connection import get_connection
from pathlib import Path

# Initialize logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

def read_etl_batch_id(source_name):
    """Read ETL batch ID generated by the batch initialization step."""

    file_path = Path("/opt/project") / "configs" / f"{source_name}_batch_id.txt"

    logger.info(
        "[BATCH] Reading batch metadata | path=%s",
        file_path,
    )

    with open(file_path, "r", encoding="utf-8") as file:
        etl_batch_id = file.readline().strip()

    logger.info(
        "[BATCH] Loaded batch_id=%s",
        etl_batch_id,
    )

    return etl_batch_id


def get_table_count(cursor, schema_name, table_name, source_system):
    """Fetches count of tables in landing"""
    logger.info(f"Getting table count for {table_name} from Postgres...")
    etl_batch_id = read_etl_batch_id(source_system)
    query = f"""
        SELECT COUNT(*) FROM {schema_name}.{table_name} WHERE etl_batch_id = '{etl_batch_id}';
    """
    try:
        cursor.execute(query)
        table_count = cursor.fetchone()[0]
        logger.info(f"Count for {schema_name}.{table_name}: {table_count}")
        return table_count
    except Exception as e:
        logger.error(f"Failed to fetch table details: {e}")
        return []


def get_source_file_count(source_name):
    """Find the latest JSON file for the given source and find the no. of rows"""
    raw_dir = Path("/opt/project") / "data" / "raw" / source_name
    logger.info(f"Checking for raw_data file in {raw_dir}")
    
    files = sorted(raw_dir.glob(f"{source_name}_*.json"))

    if files:
        latest_file = files[-1]
        file_name = latest_file.name
        logger.info(f"Using {file_name}")
        file_path = str(raw_dir)
    else:
        raise FileNotFoundError(f"No {source_name} files found in {raw_dir}")
    
    try:
        os.chdir(file_path)
        with open(file_name, "r", encoding="utf-8") as file:
            data = json.load(file)

        raw_count = len(data)

        logger.info(f"Number of records: {raw_count}")

    except Exception as e:
        logger.error(f"Couldn't read the file: {e}")
    
    return raw_count

def insert_audit_data(cursor,conn,raw_count,table_count,source_system,phase_name="landing"):
    """
    Update audit.batch_log with ANR (Audit & Reconciliation) result.
    """

    etl_batch_id = read_etl_batch_id(source_system)

    logger.info(
        "[ANR] Updating batch audit | batch_id=%s | raw_count=%s | landing_count=%s",
        etl_batch_id,
        raw_count,
        table_count,
    )

    # Determine status
    if raw_count == table_count:
        batch_status = "C"
        record_count_failed = 0
        error_message = (
            f"ANR validation passed: raw_count={raw_count}, landing_count={table_count}"
        )
    else:
        batch_status = "E"
        record_count_failed = abs(raw_count - table_count)
        error_message = (
            f"ANR validation failed: raw_count={raw_count}, landing_count={table_count}"
        )

    query = """
        UPDATE audit.batch_log
        SET
            batch_status = %s,
            record_count_processed = %s,
            record_count_failed = %s,
            error_message = %s,
            updated_at = CURRENT_TIMESTAMP
        WHERE etl_batch_id = %s
          AND phase_name = %s
          AND source_system = %s
    """

    try:
        cursor.execute(
            query,
            (
                batch_status,
                table_count,
                record_count_failed,
                error_message,
                etl_batch_id,
                phase_name,
                source_system,
            ),
        )

        conn.commit()

        logger.info(
            "[ANR] Audit updated successfully | batch_id=%s | status=%s",
            etl_batch_id,
            batch_status.upper(),
        )

        return batch_status

    except Exception:
        conn.rollback()

        logger.exception(
            "[ANR] Failed updating audit.batch_log | batch_id=%s",
            etl_batch_id,
        )

        raise
    

def main():
    """Main entry point for landing anr"""
    # Validate arguments
    if len(sys.argv) != 5:
        print("Usage: python landing_anr.py <source_name> <schema_name> <table_name> <source_system>")
        sys.exit(1)
    
    source_name = sys.argv[1]    
    schema_name = sys.argv[2]
    table_name = sys.argv[3]
    source_system = sys.argv[4]
    
    conn = None
    cursor = None

    try:
        # Connect to database
        conn = get_connection()
        if conn:
            cursor = conn.cursor()
            logger.info("Connected successfully to Postgres")
        else:
            logger.error("Can't connect to Postgres. Please check DB availability.")
            sys.exit(1)

        # Get table columns
        landing_table_count = get_table_count(cursor, schema_name, table_name, source_system)
        
        source_file_count = get_source_file_count(source_name)
        
        if not landing_table_count :
            logger.error("No data found for the specified table/schema.")
            sys.exit(1)
        if not source_file_count :
            logger.error("No data found for the source file")
            sys.exit(1)
    
        audit_status = insert_audit_data(cursor,conn,source_file_count,landing_table_count,source_system,)
        logger.info(
            "[ANR] Validation completed | status=%s",
            audit_status,
        )

        if audit_status == "E":
            logger.error(
                "[ANR] Count reconciliation failed"
            )
            sys.exit(1)

    except Exception as e:
        logger.error(f"Fatal error: {e}")
        sys.exit(1)
    finally:
        # Cleanup
        if cursor:
            cursor.close()
        if conn:
            conn.close()
        logger.info("Closed Connection to Postgres")

        
if __name__ == "__main__":
    main()